In [7]:
import numpy as n
n.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
n.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [9]:
n.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
n.arange(1,11,3)

array([ 1,  4,  7, 10])

In [11]:
n.linspace(5,25,5)

array([ 5., 10., 15., 20., 25.])

In [12]:
a=n.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [13]:
a.shape

(2, 2, 3)

In [14]:
a.ndim

3

In [15]:
a.size

12

In [16]:
a.dtype

dtype('int64')

In [17]:
a=n.array([1,2,3,4])
b=n.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [18]:
c=a*b
c

array([ 4, 10, 18, 28])

In [19]:
c.sum()

np.int64(60)

In [20]:
a.mean()

np.float64(2.5)

In [21]:
c.max()

np.int64(28)

In [22]:
c.min()

np.int64(4)

In [23]:
c.std()

np.float64(9.0)

In [24]:
c[0]

np.int64(4)

In [25]:
a=[10,20,30,40,50]
a[1:4]

[20, 30, 40]

In [26]:
a[::2]

[10, 30, 50]

In [27]:
a=n.array([[1,2,3],[4,5,6]])
a[0,1]

np.int64(2)

In [28]:
a[:,1]

array([2, 5])

In [29]:
a=n.arange(1,19)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [30]:
a.reshape((2,3,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
a=n.array([1,2,3])
a+5

array([6, 7, 8])

In [32]:
a=n.array([[1,2,3],[4,5,6],[7,8,9]])
a[:,0]


array([1, 4, 7])

In [33]:
n.full((3,3,2),7)

array([[[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]]])

In [34]:
a=n.arange(1,13)
a
a.reshape(2,2,3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
a=n.arange(1,11)
b=n.arange(11,21)
n.vstack((a,b))
n.vstack(a)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [37]:
n.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
n.stack((a,b),0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [39]:
a=n.arange(1,11)
a=a.reshape(2,5)
print(a>5)
a[a>5]

[[False False False False False]
 [ True  True  True  True  True]]


array([ 6,  7,  8,  9, 10])

In [40]:
a=n.arange(1,11)
b=n.arange(11,21)
n.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
print(a)
a[[0,2,4]]

[ 1  2  3  4  5  6  7  8  9 10]


array([1, 3, 5])

In [42]:
a=n.array([[1,2,3],[4,5,6],[7,8,9]])
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [43]:
n.sort(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
n.argmax(a)

np.int64(8)

In [45]:
n.argmin(a)

np.int64(0)

In [46]:
n.sort(a)[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [47]:
a=n.arange(1,11)
-n.sort(-a)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [48]:
a=n.array([[1,2],[3,4]])
b=n.array([[5,6],[7,8]])
a@b

array([[19, 22],
       [43, 50]])

In [49]:
n.dot(b,a)

array([[23, 34],
       [31, 46]])

In [50]:
a*b #element wise

array([[ 5, 12],
       [21, 32]])

In [51]:
(a@b).shape

(2, 2)

In [52]:
n.random.rand(3)

array([0.87271338, 0.74794457, 0.00603385])

In [53]:
n.random.rand(2,5)

array([[0.42262113, 0.21945859, 0.18003286, 0.38598819, 0.61789589],
       [0.52465418, 0.68828003, 0.52162729, 0.69917627, 0.3863294 ]])

In [54]:
n.random.randint(1,10,5)#size=5

array([1, 8, 8, 7, 5], dtype=int32)

In [55]:
n.random.randint(1,10,(2,3))#size=(2,3)

array([[3, 2, 9],
       [8, 4, 9]], dtype=int32)

In [56]:
n.random.randn(3)

array([-0.85877702, -1.05043718, -0.05797302])

In [57]:
n.random.randint(1,101,5)

array([ 3, 28, 63, 22, 83], dtype=int32)

In [58]:
a=n.arange(1,13)
a.reshape(-1,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
a=n.array([[1,2,3],[4,5,6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
a=n.array([1,2,3,4,5])
a.reshape(1,5).T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [61]:
a = n.array([[1,2,3],
              [4,5,6]])
print(n.sum(a,0))
print(n.sum(a,1))

[5 7 9]
[ 6 15]


In [62]:
a=n.arange(1,13)
a=a.reshape(2,2,3)
print(a)
n.sum(a,2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[ 6, 15],
       [24, 33]])

In [63]:
a = n.array([[1,2,3],
              [4,5,6]])

b = n.array([10,20,30])
a+b#broadcasting

array([[11, 22, 33],
       [14, 25, 36]])

broadcasting happens from right to left


In [65]:
a = n.array([[1,2],[3,4]])
a.sum(1)

array([3, 7])

In [68]:
a = n.array([10,20,30,40])

a[a > 20]


array([30, 40])

In [79]:
a = n.array([1,2,2,3,3,3])

n.unique(a)

array([1, 2, 3])

In [86]:
a = n.array([5,2,8,1])

n.sort(a)

array([1, 2, 5, 8])

In [87]:
n.sort(a)[::-1]

array([8, 5, 2, 1])

In [88]:
n.sin(a)

array([-0.95892427,  0.90929743,  0.98935825,  0.84147098])